#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/sway/i3blocks.conf together with: ~/.config/sway/scripts/power-profiles

# script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
echo "$current_profile"
